HOSTS:
  debian-9-64:
    platform: debian-9-amd64
    hypervisor: docker
    image: debian:9
    docker_preserve_image: true
    docker_image_commands:
      - 'apt-get update && apt-get -y --no-install-recommends install wget cron git php-cli php-dom php-gd php-mbstring php-pear php-sqlite php-zip'

CONFIG:
  type: foss
  log_level: info
  trace_limit: 100
