stages:
  - checks
  - deploy


lint:
  stage: checks
  script:
    - tools/puppet_lint.sh

syntax:
  stage: checks
  script:
    - tools/puppet_check_syntax_fast.sh

deploy:
  stage: deploy
  script:
    - echo Hello deploy
