#!/bin/bash
#
# List MySQL binlogs
#
# Author: Matthias Crauwels <matthias.crauwels@ugent.be>
#

MYSQL=`which mysql`

INDEX_FILE=`${MYSQL} --execute="SHOW GLOBAL VARIABLES LIKE 'log_bin_index'" -BN | cut -d$'\t' -f2`
LOG_FILE_DIR=`dirname ${INDEX_FILE}`

echo $INDEX_FILE

for LINE in `cat $INDEX_FILE`;
do
  echo ${LINE/./$LOG_FILE_DIR}
done
