name    'root-mailserver'
version '0.0.1'
source 'https://github.com/root/puppet-mailserver'
author 'root'
license 'Apache-2.0'
summary ''
description ''
project_page 'https://github.com/root/puppet-mailserver'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
